spring:
  profiles:
    active: development
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: development
server:
  scheme: "http"
  host: localhost
  port: 8080
---
spring:
  config:
    activate:
      on-profile: newprofile
server:
  scheme: "http"
  host: 127.0.0.1
  port: 8080
---
api-version:
  v1: "/api/v1"

